spring:
  application:
    name: microservice-eureka-server

server.port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${APPLICATION_DOMAIN:peer1}
    nonSecurePort: 80