server.port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${server.port:8761}/eureka/
  instance:
    hostname: ${APPLICATION_DOMAIN:127.0.0.1}
    nonSecurePort: 80